# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
import numpy as np
import pandas as pd
import io
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns;

import warnings
warnings.filterwarnings("ignore")

In [0]:
iris = datasets.load_iris()

In [6]:
iris_df = pd.DataFrame(data=iris.data, index=None, columns=iris.feature_names)
iris_target = pd.DataFrame(data=iris.target)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
iris_df.shape

(150, 4)

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris.data
Y = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(iris_df, iris_target, test_size=0.25, random_state=1)

In [11]:
x_train.shape

(112, 4)

In [12]:
x_test.shape

(38, 4)

In [13]:
y_train.shape

(112, 1)

In [14]:
y_test.shape

(38, 1)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

In [0]:
y_train = pd.DataFrame(onehotencoder.fit_transform(y_train).toarray())
y_test = pd.DataFrame(onehotencoder.fit_transform(y_test).toarray())

In [17]:
y_train.head()

0    1    2
0  0.0  1.0  0.0
1  0.0  0.0  1.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0
4  0.0  0.0  1.0

In [18]:
y_test.head()

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  1.0  0.0
3  1.0  0.0  0.0
4  0.0  0.0  1.0

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [0]:
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(Dense(15, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [23]:
len(model.layers)

2

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                75        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 48        
Total params: 123
Trainable params: 123
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [25]:
model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 6ms/sample - loss: 1.1872 - accuracy: 0.3929 - val_loss: 0.7544 - val_accuracy: 0.6053
Epoch 2/100
112/112 [==============================] - 0s 179us/sample - loss: 0.7293 - accuracy: 0.7143 - val_loss: 0.6903 - val_accuracy: 0.6316
Epoch 3/100
112/112 [==============================] - 0s 204us/sample - loss: 0.6696 - accuracy: 0.7143 - val_loss: 0.6679 - val_accuracy: 0.6053
Epoch 4/100
112/112 [==============================] - 0s 202us/sample - loss: 0.6473 - accuracy: 0.8036 - val_loss: 0.6714 - val_accuracy: 0.5789
Epoch 5/100
112/112 [==============================] - 0s 217us/sample - loss: 0.6332 - accuracy: 0.6964 - val_loss: 0.6224 - val_accuracy: 0.9737
Epoch 6/100
112/112 [==============================] - 0s 173us/sample - loss: 0.6304 - accuracy: 0.9018 - val_loss: 0.6640 - val_accuracy: 0.5789
Epoch 7/100
112/112 [==============================] - 0s 199us/sample - lo

In [26]:
score=model.evaluate(x_test,y_test)

38/38 [==============================] - 0s 150us/sample - loss: 0.3559 - accuracy: 0.8684


In [27]:
score

[0.3558925578468724, 0.8684211]

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = np.round(model.predict(x_test))


In [29]:
y_pred[0:10]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [31]:
score = model.evaluate(x_test, y_test,verbose=1)

print(score)


38/38 [==============================] - 0s 236us/sample - loss: 0.3559 - accuracy: 0.8684
[0.3558925578468724, 0.8684211]


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
x_test=x_test.reset_index()


In [47]:
x_test.head()

index  sepal length (cm)  ...  petal length (cm)  petal width (cm)
0     14                5.8  ...                1.2               0.2
1     98                5.1  ...                3.0               1.1
2     75                6.6  ...                4.4               1.4
3     16                5.4  ...                1.3               0.4
4    131                7.9  ...                6.4               2.0

[5 rows x 5 columns]

IndexError: ignored



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
uploaded = files.upload()

Saving prices.csv to prices.csv


In [0]:
df = pd.read_csv(io.BytesIO(uploaded['prices.csv']))
df_original = pd.read_csv(io.BytesIO(uploaded['prices.csv']))
df.shape

(851264, 7)

In [0]:
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [0]:
df.describe().transpose()

count          mean  ...           75%           max
open    851264.0  7.083699e+01  ...  7.988000e+01  1.584440e+03
close   851264.0  7.085711e+01  ...  7.989000e+01  1.578130e+03
low     851264.0  7.011841e+01  ...  7.911000e+01  1.549940e+03
high    851264.0  7.154348e+01  ...  8.061000e+01  1.600930e+03
volume  851264.0  5.415113e+06  ...  5.222500e+06  8.596434e+08

[5 rows x 8 columns]

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df = df.drop(labels=["date","symbol"], axis=1)

In [0]:
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [0]:
df.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df_sub = df[:1000]

In [0]:
df_sub.shape

(1000, 5)

First 1000 records obtained


## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = df_sub[["open", "close", "low", "high"]]
Y = (df_sub[["volume"]]/1000000)

In [0]:
X.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [0]:
Y.head()

volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
x = X.to_numpy()
y = Y.to_numpy()

In [0]:
x = x.astype("float32")
y = y.astype("float32")

In [0]:
x.dtype

dtype('float32')

In [0]:
y.dtype

dtype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
x=tf.math.l2_normalize(x)

In [0]:
x

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(features, W, b):     
  y_pred = tf.add(tf.matmul(features, W), b)     
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function 
def loss(y_actual, y_pred):     
  diff = y_actual - y_pred     
  sqre = tf.square(diff)     
  average = tf.reduce_mean(sqre)     
  return average

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_act, w, b, lr=0.01):          
  # Record mathematical operations on 'tape' to calculate loss     
  with tf.GradientTape() as t:         
    t.watch([w,b])         
    current_pred = prediction(x, w, b)         
    current_loss = loss(y_act, current_pred)          
    
    # Calculate Gradients for Loss with respect to Weights and Bias     
    dw, db = t.gradient(current_loss,[w, b])          
    
    # Update Weights and Bias     
    w = w - lr * dw     
    b = b - lr * db          
    return w, b     

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
for i in range(100):         
      W, b = train(x, y, W, b)     
      print('Current Training Loss on iteration is:', i, loss(y, prediction(x, W, b)).numpy())

Current Training Loss on iteration is: 0 236.16805
Current Training Loss on iteration is: 1 235.09369
Current Training Loss on iteration is: 2 234.06194
Current Training Loss on iteration is: 3 233.07103
Current Training Loss on iteration is: 4 232.1194
Current Training Loss on iteration is: 5 231.20547
Current Training Loss on iteration is: 6 230.32773
Current Training Loss on iteration is: 7 229.48479
Current Training Loss on iteration is: 8 228.67525
Current Training Loss on iteration is: 9 227.89775
Current Training Loss on iteration is: 10 227.1511
Current Training Loss on iteration is: 11 226.43398
Current Training Loss on iteration is: 12 225.7453
Current Training Loss on iteration is: 13 225.08394
Current Training Loss on iteration is: 14 224.4487
Current Training Loss on iteration is: 15 223.83865
Current Training Loss on iteration is: 16 223.25282
Current Training Loss on iteration is: 17 222.69019
Current Training Loss on iteration is: 18 222.14984
Current Training Loss on i

### Observe values of Weight
- Print the updated values

In [0]:
print(W)

tf.Tensor(
[[0.0194333 ]
 [0.01969694]
 [0.01937149]
 [0.01976266]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [0]:
print(b)

tf.Tensor([4.608607], shape=(1,), dtype=float32)
